# Generated by Django 4.0.1 on 2022-04-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='projectalbum',
            name='album_image',
            field=models.ImageField(upload_to='album_images/'),
        ),
    ]
