# Generated by Django 4.0.1 on 2022-04-14 16:30

import django.core.validators
from django.db import migrations, models
import progress_app.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressappuser',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(5), progress_app.common.validators.validate_letters]),
        ),
    ]
